name: pln_mobile_clone
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  core:
    path: packages/core
  style_resources:
    path: packages/style_resources
  onboarding: 
    path: packages/features/onboarding
  signin: 
    path: packages/features/signin
  signup: 
    path: packages/features/signup
  beranda: 
    path: packages/features/beranda
  bottom_navigation: 
    path: packages/features/bottom_navigation
  activity: 
    path: packages/features/activity
  point: 
    path: packages/features/point
  notification: 
    path: packages/features/notification
  profile: 
    path: packages/features/profile
  
  cupertino_icons: ^1.0.2
  get_it: ^7.2.0
  shared_preferences: ^2.0.15
  flutter_screenutil: ^5.6.0
  provider: ^6.0.5
  go_router: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.0

flutter:  
  uses-material-design: true
  assets:
  - assets/