name: bottom_navigation
publish_to: none

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  style_resources:
    path: ../../style_resources
  components_library:
    path: ../../components_library
  go_router: ^6.0.1
  flutter_svg: ^1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:

  assets:
    - assets/
  